# Generated by Django 3.0.5 on 2020-04-19 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_todolist_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='file',
        ),
    ]
