# Generated by Django 3.0.5 on 2020-04-19 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_todolist_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'verbose_name': 'ToDo List', 'verbose_name_plural': 'ToDo Lists'},
        ),
    ]
