# Generated by Django 3.0.5 on 2020-04-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200419_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
