# Generated by Django 3.0.5 on 2020-04-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'SuperAdmin'), (2, 'Guest')], default=2),
        ),
    ]
